//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComProvis.Api.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public int ProductID { get; set; }
        public int DiskSize { get; set; }
        public byte DiskSizeUnitID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int NumOfUsers { get; set; }
        public bool IsLocked { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string ExternalProductId { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
